//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPRO_SportSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPRO_SportSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vážený zákazniku,
        ///z Vašeho účtu na http://sportsoft.azurewebsites.net/ byl odeslán požadavek na změnu hesla. 
        ///
        ///Vaše nové heslo je:
        ///{0}
        ///
        ///Po přihlášení si toto heslo, prosím, změňte.
        ///
        ///Děkujeme..
        /// </summary>
        internal static string EForgPass {
            get {
                return ResourceManager.GetString("EForgPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noreply@gmail.com.
        /// </summary>
        internal static string EFrom {
            get {
                return ResourceManager.GetString("EFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        internal static string EHost {
            get {
                return ResourceManager.GetString("EHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noreplysportsoft@gmail.com.
        /// </summary>
        internal static string ELogin {
            get {
                return ResourceManager.GetString("ELogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rpro2016.
        /// </summary>
        internal static string EPass {
            get {
                return ResourceManager.GetString("EPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        internal static string EPort {
            get {
                return ResourceManager.GetString("EPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vážený zákazníku, 
        ///Váš účet {0} na našich stránkách byl úspěšně vytvořen.
        ///Nyní se můžete přihlásit na http://sportsoft.azurewebsites.net/. 
        ///
        ///Děkujeme..
        /// </summary>
        internal static string EReg {
            get {
                return ResourceManager.GetString("EReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vážený zákazniku,
        ///Vaše rezervace kurtu {0} dne {1} v {2} na našem portále byla úspěšně vytvořena.
        ///Rezervace proběhla pro {3} týden/týdnů.
        ///Rezervaci můžete zrušit nejpozději 24 hodin před začátkem na webu http://sportsoft.azurewebsites.net/.
        ///
        ///Děkujeme..
        /// </summary>
        internal static string ERes {
            get {
                return ResourceManager.GetString("ERes", resourceCulture);
            }
        }
    }
}
