<?xml version="1.0" encoding="utf-8"?><Database Name="SportSoftDb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=rpro.database.windows.net;Initial Catalog=SportSoftDb;Integrated Security=False;User ID=SportSoft;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SportSoftDbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Courts" Member="Courts">
    <Type Name="Court">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Sports_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Court_Reservation" Member="Reservations" ThisKey="Id" OtherKey="Courts_Id" Type="Reservation" />
      <Association Name="Sport_Court" Member="Sport" ThisKey="Sports_Id" OtherKey="Id" Type="Sport" IsForeignKey="true" />
      <Association Name="PriceLists_Courts_Court" Member="PriceLists_Courts" ThisKey="Id" OtherKey="Courts_Id" Type="PriceLists_Courts" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sports" Member="Sports">
    <Type Name="Sport">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Image_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sport_Court" Member="Courts" ThisKey="Id" OtherKey="Sports_Id" Type="Court" />
      <Association Name="Image_Sport" Member="Image" ThisKey="Image_Id" OtherKey="Id" Type="Image" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User" Member="Users">
    <Type Name="User">
      <Column Name="Email" Type="System.String" DbType="VarChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Salt" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="User_Reservation" Member="Reservations" ThisKey="Email" OtherKey="User_Email" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.PriceLists" Member="PriceLists">
    <Type Name="PriceList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="PriceLists_Courts_PriceList" Member="PriceLists_Courts" ThisKey="Id" OtherKey="PriceLists_Id" Type="PriceLists_Courts" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PriceLists_Courts" Member="PriceLists_Courts">
    <Type Name="PriceLists_Courts">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PriceList_Id" Member="PriceLists_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Courts_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="false" />
      <Association Name="PriceLists_Courts_Court" Member="Courts" ThisKey="Courts_Id" OtherKey="Id" Type="Court" />
      <Association Name="PriceLists_Courts_PriceList" Member="PriceLists" ThisKey="PriceLists_Id" OtherKey="Id" Type="PriceList" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation_Time" Member="Reservation_Times">
    <Type Name="Reservation_Time">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Time" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Reservation_Time_Reservation" Member="Reservations" ThisKey="Id" OtherKey="Time_Id" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.Reservations" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Courts_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Court_Reservation" Member="Court" ThisKey="Courts_Id" OtherKey="Id" Type="Court" IsForeignKey="true" />
      <Association Name="Reservation_Time_Reservation" Member="Reservation_Time" ThisKey="Time_Id" OtherKey="Id" Type="Reservation_Time" IsForeignKey="true" />
      <Association Name="User_Reservation" Member="User" ThisKey="User_Email" OtherKey="Email" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Image" Member="Images">
    <Type Name="Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImageName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ImageBytes" Type="System.Byte[]" DbType="VARBINARY (max)" CanBeNull="false" />
      <Association Name="Image_Sport" Member="Sports" ThisKey="Id" OtherKey="Image_Id" Type="Sport" />
    </Type>
  </Table>
</Database>